require_relative 'mailgun/api/messages'
require_relative 'mailgun/api'
require_relative 'mailgun/client'
require_relative 'mailgun/exception'
require_relative 'mailgun/message'
require_relative 'mailgun/response'